# Servers Overview relies upon.
#
# Usage: `docker-compose start` to create a dev/test environment.
#
# Services:
#   * :9010 -> Postgres
#   * :9020 -> Redis

version: "3"

volumes:
  overview-dev-database-data:

services:
  overview-dev-redis:
    container_name: overview-dev-redis 
    image: redis:2.8
    ports:
      - "9020:6379"

  overview-dev-database:
    container_name: overview-dev-database
    image: overview/database
    volumes:
      - overview-dev-database-data:/var/lib/postgresql/data
    ports:
      - "9010:5432"
