# Servers Overview relies upon.
#
# Usage: `docker-compose start` to create a dev/test environment.

version: "3"

volumes:
  database-data:
  search-data:
  blob-storage-data:
  homedir:

services:
  redis:
    build: ./docker/redis

  database:
    build: ./docker/database
    volumes:
      - database-data:/var/lib/postgresql/data

  dev:
    build: ./docker/overview-dev
    stdin_open: true
    volumes:
      - search-data:/var/lib/overview/search
      - blob-storage-data:/var/lib/overview/blob-storage
      - homedir:/root # sbt's and npm's caches
      #- .:/app:ro
      - .:/app # we can't go "ro" because Webpack writes to the source directory for now
    ports:
      - '127.0.0.1:3333:3333' # port 3333 is useful when running integration-test/mock-plugins/standalone
      - '127.0.0.1:9000:80'
