# Servers Overview relies upon.
#
# Usage: `docker-compose start` to create a dev/test environment.

version: "3"

volumes:
  database-data:
  search-data:
  blob-storage-data:
  homedir:

services:
  redis:
    image: overview/redis

  database:
    image: overview/database
    volumes:
      - database-data:/var/lib/postgresql/data

  dev:
    build: ./docker/overview-dev
    image: overview-dev
    stdin_open: true
    volumes:
      - search-data:/var/lib/overview/search
      - blob-storage-data:/var/lib/overview/blob-storage
      - homedir:/root # sbt's and npm's caches
      #- .:/app:ro
      - .:/app # we can't go "ro" because Webpack writes to the source directory for now
    ports:
      - '127.0.0.1:9000:80'
