---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-ingress-aws-controller-serviceaccount
  namespace: kube-system
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kube-ingress-aws-controller
  namespace: kube-system
  labels:
    application: kube-ingress-aws-controller
    component: ingress
spec:
  replicas: 1
  selector:
    matchLabels:
      application: kube-ingress-aws-controller
      component: ingress
  template:
    metadata:
      labels:
        application: kube-ingress-aws-controller
        component: ingress
      annotations:
        iam.amazonaws.com/role: ENVIRONMENT-kube-ingress-alb
    spec:
      serviceAccountName: kube-ingress-aws-controller-serviceaccount
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      containers:
      - name: controller
        image: registry.opensource.zalan.do/teapot/kube-ingress-aws-controller:v0.8.3
        args:
        - -stack-termination-protection
        env:
        - name: AWS_REGION
          value: us-east-1
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: kube-ingress-aws-controller-clusterrole
  namespace: kube-system
rules:
- apiGroups: ["extensions"]
  resources: ["ingresses"]
  verbs: ["get","watch","list"]
- apiGroups: ["extensions"]
  resources: ["ingresses/status"]
  verbs: ["patch"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get","watch","list"]
- apiGroups: [""]
  resources: ["endpoints"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: kube-ingress-aws-controller-clusterrolebinding
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kube-ingress-aws-controller-clusterrole
subjects:
- kind: ServiceAccount
  name: kube-ingress-aws-controller-serviceaccount
  namespace: kube-system
