version: '3.2'

services:
  overview-web:
    image: overview-web:${OVERVIEW_VERSION}
    networks: [ 'default', 'database', 'redis', 'worker' ]
    depends_on: [ 'overview-database', 'overview-redis', 'overview-worker' ]
    environment:
      - REDIS_HOST=overview-redis
      - DATABASE_SERVER_NAME=overview-database
      - BLOB_STORAGE_FILE_BASE_DIRECTORY=/var/lib/overview/blob-storage
      - MESSAGE_BROKER_HOSTNAME=overview-worker
      - MESSAGE_BROKER_CLIENT_HOSTNAME=overview-web
    volumes:
      - blob-storage:/var/lib/overview/blob-storage

  overview-worker:
    image: overview-worker:${OVERVIEW_VERSION}
    networks: [ 'database', 'worker' ]
    depends_on: [ 'overview-database' ]
    volumes:
      - blob-storage:/var/lib/overview/blob-storage
    environment:
      - DATABASE_SERVER_NAME=overview-database
      - BLOB_STORAGE_FILE_BASE_DIRECTORY=/var/lib/overview/blob-storage
      - MESSAGE_BROKER_HOSTNAME=overview-worker

  overview-database:
    image: overview-database:${OVERVIEW_VERSION}
    networks: [ 'database' ]

  overview-redis:
    image: overview-redis:${OVERVIEW_VERSION}
    networks: [ 'redis' ]

  overview-db-evolution-applier:
    image: overview-db-evolution-applier:${OVERVIEW_VERSION}
    networks: [ 'database' ]
    depends_on: [ 'overview-database' ]
    environment:
      - DATABASE_SERVER_NAME=overview-database

  overview-integration-test:
    image: overview-integration-test:${OVERVIEW_VERSION}
    volumes:
      - '../integration-test/test-results.xml:/integration-test/test-results.xml'
    depends_on: [ 'overview-web' ]

networks:
  database:
  redis:
  worker:

# Most data is transient. only one directory is shared.
volumes:
  blob-storage:
