apiVersion: v1
kind: Service
metadata:
  name: overview-database
spec:
  ports:
  - port: 5432
  selector:
    app: postgres
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pv-claim
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - image: REPOSITORY/overview-database:latest
        # Use :latest, not SHA1, so we don't try to roll over if we re-run ./start.sh
        name: postgres
        ports:
        - containerPort: 5432
          name: postgres
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
        # initdb will complain about lost+found unless we use a subdir.
        # We ought to be using a subdir anyway, for a version number.
        # https://github.com/docker-library/postgres/issues/263
        # https://github.com/docker-library/postgres/issues/201
        env:
        - name: PGDATA
          value: /var/lib/postgresql/data/9.4
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pv-claim
